// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: dispatch/dispatch.proto

package dispatch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassengerId string  `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	PickupLat   float64 `protobuf:"fixed64,2,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLong  float64 `protobuf:"fixed64,3,opt,name=pickup_long,json=pickupLong,proto3" json:"pickup_long,omitempty"`
	DropoffLat  float64 `protobuf:"fixed64,4,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLong float64 `protobuf:"fixed64,5,opt,name=dropoff_long,json=dropoffLong,proto3" json:"dropoff_long,omitempty"`
	VehicleType string  `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"` // e.g., "go-car", "go-ride"
}

func (x *RequestRideRequest) Reset() {
	*x = RequestRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dispatch_dispatch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRideRequest) ProtoMessage() {}

func (x *RequestRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_dispatch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRideRequest.ProtoReflect.Descriptor instead.
func (*RequestRideRequest) Descriptor() ([]byte, []int) {
	return file_dispatch_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRideRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *RequestRideRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *RequestRideRequest) GetPickupLong() float64 {
	if x != nil {
		return x.PickupLong
	}
	return 0
}

func (x *RequestRideRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *RequestRideRequest) GetDropoffLong() float64 {
	if x != nil {
		return x.DropoffLong
	}
	return 0
}

func (x *RequestRideRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type RequestRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "SEARCHING", "NO_DRIVERS_FOUND"
}

func (x *RequestRideResponse) Reset() {
	*x = RequestRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dispatch_dispatch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRideResponse) ProtoMessage() {}

func (x *RequestRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_dispatch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRideResponse.ProtoReflect.Descriptor instead.
func (*RequestRideResponse) Descriptor() ([]byte, []int) {
	return file_dispatch_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *RequestRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *RequestRideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_dispatch_dispatch_proto protoreflect.FileDescriptor

var file_dispatch_dispatch_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x22, 0xde, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61,
	0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x4c, 0x61, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x64, 0x72, 0x6f, 0x70, 0x6f, 0x66, 0x66, 0x4c, 0x6f, 0x6e,
	0x67, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x46, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x69,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x5d, 0x0a, 0x0f,
	0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4a, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x69, 0x64, 0x65, 0x12, 0x1c,
	0x2e, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x77, 0x69, 0x6b, 0x69, 0x6b,
	0x75, 0x73, 0x75, 0x6d, 0x61, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dispatch_dispatch_proto_rawDescOnce sync.Once
	file_dispatch_dispatch_proto_rawDescData = file_dispatch_dispatch_proto_rawDesc
)

func file_dispatch_dispatch_proto_rawDescGZIP() []byte {
	file_dispatch_dispatch_proto_rawDescOnce.Do(func() {
		file_dispatch_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(file_dispatch_dispatch_proto_rawDescData)
	})
	return file_dispatch_dispatch_proto_rawDescData
}

var file_dispatch_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dispatch_dispatch_proto_goTypes = []interface{}{
	(*RequestRideRequest)(nil),  // 0: dispatch.RequestRideRequest
	(*RequestRideResponse)(nil), // 1: dispatch.RequestRideResponse
}
var file_dispatch_dispatch_proto_depIdxs = []int32{
	0, // 0: dispatch.DispatchService.RequestRide:input_type -> dispatch.RequestRideRequest
	1, // 1: dispatch.DispatchService.RequestRide:output_type -> dispatch.RequestRideResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatch_dispatch_proto_init() }
func file_dispatch_dispatch_proto_init() {
	if File_dispatch_dispatch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dispatch_dispatch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dispatch_dispatch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dispatch_dispatch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatch_dispatch_proto_goTypes,
		DependencyIndexes: file_dispatch_dispatch_proto_depIdxs,
		MessageInfos:      file_dispatch_dispatch_proto_msgTypes,
	}.Build()
	File_dispatch_dispatch_proto = out.File
	file_dispatch_dispatch_proto_rawDesc = nil
	file_dispatch_dispatch_proto_goTypes = nil
	file_dispatch_dispatch_proto_depIdxs = nil
}
