// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID          pgtype.UUID        `json:"id"`
	WalletID    string             `json:"wallet_id"`
	Amount      float64            `json:"amount"`
	Description string             `json:"description"`
	ReferenceID pgtype.Text        `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	UserID    string             `json:"user_id"`
	Balance   float64            `json:"balance"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
