// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// internal/wallet/db/query/wallet.sql
	CreateWallet(ctx context.Context, userID string) (Wallet, error)
	GetWallet(ctx context.Context, userID string) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
