// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWalletBalance = `-- name: AddWalletBalance :one
UPDATE wallets
SET balance = balance + $1, -- SQLC will generate 'Amount' param
    updated_at = NOW()
WHERE user_id = $2
    RETURNING user_id, balance, updated_at
`

type AddWalletBalanceParams struct {
	Amount float64 `json:"amount"`
	UserID string  `json:"user_id"`
}

func (q *Queries) AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, addWalletBalance, arg.Amount, arg.UserID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    wallet_id, amount, description, reference_id
) VALUES (
             $1, $2, $3, $4
         ) RETURNING id, wallet_id, amount, description, reference_id, created_at
`

type CreateTransactionParams struct {
	WalletID    string      `json:"wallet_id"`
	Amount      float64     `json:"amount"`
	Description string      `json:"description"`
	ReferenceID pgtype.Text `json:"reference_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WalletID,
		arg.Amount,
		arg.Description,
		arg.ReferenceID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Description,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one

INSERT INTO wallets (
    user_id, balance
) VALUES (
             $1, 0.0
         ) RETURNING user_id, balance, updated_at
`

// internal/wallet/db/query/wallet.sql
func (q *Queries) CreateWallet(ctx context.Context, userID string) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, balance, updated_at FROM wallets
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWallet(ctx context.Context, userID string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}
