// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	PassengerID string             `json:"passenger_id"`
	DriverID    string             `json:"driver_id"`
	PickupLat   float64            `json:"pickup_lat"`
	PickupLong  float64            `json:"pickup_long"`
	DropoffLat  float64            `json:"dropoff_lat"`
	DropoffLong float64            `json:"dropoff_long"`
	Status      string             `json:"status"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
