// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Order struct {
	ID          string
	PassengerID string
	DriverID    string
	PickupLat   float64
	PickupLong  float64
	DropoffLat  float64
	DropoffLong float64
	Status      string
	Price       float64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
