// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
    id, passenger_id, driver_id,
    pickup_lat, pickup_long, dropoff_lat, dropoff_long,
    status, price
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9
         ) RETURNING id, passenger_id, driver_id, pickup_lat, pickup_long, dropoff_lat, dropoff_long, status, price, created_at, updated_at
`

type CreateOrderParams struct {
	ID          string  `json:"id"`
	PassengerID string  `json:"passenger_id"`
	DriverID    string  `json:"driver_id"`
	PickupLat   float64 `json:"pickup_lat"`
	PickupLong  float64 `json:"pickup_long"`
	DropoffLat  float64 `json:"dropoff_lat"`
	DropoffLong float64 `json:"dropoff_long"`
	Status      string  `json:"status"`
	Price       float64 `json:"price"`
}

// internal/order/db/query/order.sql
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.PassengerID,
		arg.DriverID,
		arg.PickupLat,
		arg.PickupLong,
		arg.DropoffLat,
		arg.DropoffLong,
		arg.Status,
		arg.Price,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.PickupLat,
		&i.PickupLong,
		&i.DropoffLat,
		&i.DropoffLong,
		&i.Status,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, passenger_id, driver_id, pickup_lat, pickup_long, dropoff_lat, dropoff_long, status, price, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.PickupLat,
		&i.PickupLong,
		&i.DropoffLat,
		&i.DropoffLong,
		&i.Status,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderDriver = `-- name: UpdateOrderDriver :exec
UPDATE orders
SET driver_id = $2, status = 'MATCHED', updated_at = NOW()
WHERE id = $1
`

type UpdateOrderDriverParams struct {
	ID       string `json:"id"`
	DriverID string `json:"driver_id"`
}

func (q *Queries) UpdateOrderDriver(ctx context.Context, arg UpdateOrderDriverParams) error {
	_, err := q.db.Exec(ctx, updateOrderDriver, arg.ID, arg.DriverID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
